language: python

sudo: false

python:
  - '2.6'
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
- make test
- flake8 trepan_deparse/deparser.py
